import { NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth/tenant-context";
import { prisma } from "@/lib/prisma";
import { paperclipAdapter } from "@/lib/adapters/paperclip";

export async function POST(request: Request) {
  const { tenantId, userId } = await getTenantContext();
  const body = await request.json();

  const output = await paperclipAdapter.generateContent({
    tenantId,
    userId,
    agentType: body.agentType ?? "Content Writer Agent",
    campaignId: body.campaignId,
    topic: body.topic ?? body.prompt ?? "Campaign update",
    channels: body.channels ?? ["LinkedIn"],
    tone: body.tone ?? "professional",
    contentType: body.contentType ?? "post",
    brandVoice: body.brandVoice,
    prompt: body.prompt
  });

  const content = await prisma.contentItem.create({
    data: {
      tenantId,
      campaignId: body.campaignId,
      createdById: userId,
      title: output.title,
      contentType: body.contentType ?? "post",
      channels: body.channels ?? ["LinkedIn"],
      body: output.body,
      prompt: body.prompt ?? body.topic,
      tone: body.tone ?? "professional",
      status: "AI_GENERATED",
      aiMetadata: { ...output, approvalRequired: true }
    }
  });

  await prisma.contentVersion.create({
    data: {
      tenantId,
      contentItemId: content.id,
      version: 1,
      body: content.body,
      editedById: userId,
      changeSummary: "Generated by Paperclip mock adapter"
    }
  });

  return NextResponse.json({ content, output }, { status: 201 });
}
